assethub/assethub/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
import django.contrib.auth.views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$', django.contrib.auth.views.login, name='login'),
    url(r'^accounts/logout/$', django.contrib.auth.views.logout, name='logout'),
    url(r'^accounts/changepassword/$', django.contrib.auth.views.password_change, name='chane_password'),
    url(r'^accounts/changepassword/done/$', django.contrib.auth.views.password_change_done, name='password_change_done'),
    url(r'^accounts/resetpassword/$', django.contrib.auth.views.password_reset, name='reset_password'),
    url(r'^accounts/resetpassword/done/$', django.contrib.auth.views.password_reset_done, name='password_reset_done'),
    #url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
    url(r'^comments/', include('django_comments.urls')),
    url('', include('social_django.urls', namespace='social')),
    url(r'^', include('assets.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

assethub/assets/urls.py
from django.conf.urls import url, include

#from rest_framework import routers
import notifications.urls

import views.common
import views.asset
import views.users
import rest
#import serializers

#router = routers.DefaultRouter()
#router.register(r'assets', serializers.AssetViewSet)

urlpatterns = [
    url(r'^$', views.asset.index, name='index'),
    url(r'^api/auth/', include('rest_framework.urls', namespace='rest_framework')),
#    url(r'^api/', include(router.urls)),
    url(r'^api/search/$', rest.SearchList.as_view()),
    url(r'^api/applications/(?P<appslug>[-\w]+)/$', rest.ComponentList.as_view()),
    url(r'^api/applications/$', rest.ApplicationList.as_view()),
    url(r'^api/licenses/$', rest.LicenseList.as_view()),
    url(r'^api/assets/$', rest.AssetList.as_view()),
    url(r'^api/assets/(?P<pk>\d+)/$', rest.AssetDetail.as_view()),
    url(r'^api/assets/(?P<appslug>[-\w]+)/$', rest.AssetList.as_view()),
    url(r'^api/assets/(?P<appslug>[-\w]+)/(?P<cslug>[-\w]+)/$', rest.AssetList.as_view()),
    url(r'^api/tags/$', rest.TagList.as_view()),
    url(r'^search/$', views.asset.simple_search, name='simple_search'),
    url(r'^search/advanced/$', views.asset.advanced_search, name='advanced_search'),
    url(r'^tag/(?P<slug>[-\w]+)/$', views.asset.by_tag, name='by_tag'),
    url(r'^asset/(?P<pk>[0-9]+)/$', views.asset.asset_details, name='asset'),
    url(r'^asset/(?P<pk>[0-9]+)/edit/$', views.asset.edit_asset, name='edit_asset'),
    url(r'^vote/(?P<asset_id>[0-9]+)/(?P<direction>up|down)/$', views.asset.vote, name='vote'),
    url(r'^license/(?P<slug>[-\w]+)/$', views.asset.license, name='license'),
    url(r'^accounts/api/', views.common.enable_api, name='enable_api'),
    url(r'^accounts/profile/(?P<username>[-\w.]+)/follow/$', views.users.follow, name='follow_user'),
    url(r'^accounts/profile/(?P<username>[-\w.]+)/unfollow/$', views.users.unfollow, name='unfollow_user'),
    url(r'^accounts/profile/(?P<username>[-\w.]+)/feed/$', views.asset.get_user_feed, name='user_feed'),
    url(r'^accounts/profile/edit/$', views.users.edit_profile, name='edit_profile'),
    url(r'^accounts/profile/(?P<username>[-\w.]+)$', views.users.user_profile, name='user_profile'),
    url(r'^accounts/profile/$', views.users.current_user_profile, name='current_user_profile'),
    url(r'^accounts/$', views.users.get_users_list, name='users_list'),
    url(r'^post/(?P<appslug>[-\w]+)/(?P<cslug>[-\w]+)/$', views.asset.post_asset, name='post_asset'),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^notifications/', include(notifications.urls, namespace='notifications')),
    url(r'^__nonexistent__/$', views.common.nonexisting_template),
    url(r'^(?P<appslug>[-\w]+)/$', views.asset.by_application, name='by_application'),
    url(r'^(?P<appslug>[-\w]+)/version/(?P<verstring>[0-9.]+)/$', views.asset.by_version, name='by_version'),
    url(r'^(?P<appslug>[-\w]+)/(?P<cslug>[-\w]+)/version/(?P<verstring>[0-9.]+)/$', views.asset.by_component_version, name='by_component_version'),
    url(r'^(?P<appslug>[-\w]+)/tag/(?P<tslug>[-\w]+)/$', views.asset.by_app_tag, name='by_app_tag'),
    url(r'^(?P<appslug>[-\w]+)/(?P<cslug>[-\w]+)/$', views.asset.by_component, name='by_component'),
    url(r'^(?P<appslug>[-\w]+)/(?P<cslug>[-\w]+)/tag/(?P<tslug>[-\w]+)/$', views.asset.by_component_tag, name='by_component_tag')
]

assethub/assets/models.py
from __future__ import unicode_literals

from os.path import basename, join, splitext
from glob import fnmatch
from hashlib import sha1

from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.core.exceptions import ValidationError
from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import send_mail
from django.contrib.auth.models import User, Group
from django.contrib.contenttypes.models import ContentType
from django.contrib.sites.models import Site
from django_comments.models import Comment
#from django.contrib.sites import get_current_site
from django.utils.translation import ugettext_lazy as _, pgettext_lazy, ugettext
from django.utils import timezone
from django.template import loader
#from django.urls import reverse

from taggit_autosuggest.managers import TaggableManager
from vote.managers import VotableManager
from versionfield import VersionField
from notifications.signals import notify

from assets.thumbnailers import get_thumbnailer_classes, get_default_thumbnailer, get_thumbnailer, thumbnail_from_big_image

def get_api_group_name():
    # TODO: this should be configurable
    return "API Access"

def get_path(prefix, instance, filename):
    name,ext = splitext(filename)
    hash = sha1(str(timezone.now())).hexdigest()[:6]
    filename = '{}_{}{}'.format(name, hash, ext)
    return join(prefix, filename)

def get_thumbnail_path(instance, filename):
    return get_path('thumbnails/', instance, filename)

def get_big_image_path(instance, filename):
    return get_path('bigimages/', instance, filename)

def get_data_path(instance, filename):
    return get_path('data/', instance, filename)

def get_logo_path(instance, filename):
    return get_path('logos/', instance, filename)

class Application(models.Model):
    class Meta:
        verbose_name = _("application")
        verbose_name_plural = _("applications")

    slug = models.SlugField(max_length=32, primary_key=True)
    title = models.CharField(max_length=255, verbose_name=_("title"))
    notes = models.TextField(null=True, blank=True, verbose_name=_("notes"))
    logo = models.ImageField(upload_to=get_logo_path, null=True, blank=True, verbose_name=_("application logo"))
    url = models.URLField(null=True, blank=True, verbose_name=_("URL"))

    def __str__(self):
        return self.title.encode('utf-8')

    def __unicode__(self):
        return self.title

class Component(models.Model):
    class Meta:
        verbose_name = _("component")
        verbose_name_plural = _("components")
        
    application = models.ForeignKey('Application', on_delete=models.CASCADE, verbose_name=_("application"))
    slug = models.SlugField(max_length=32, primary_key=True)
    title = models.CharField(max_length=255, verbose_name=_("title"))
    notes = models.TextField(null=True, blank=True, verbose_name=_("notes"))
    upload_instructions = models.TextField(null=True, blank=True, verbose_name=_("Upload instructions"))
    install_instructions = models.TextField(null=True, blank=True, verbose_name=_("Installation instructions"))
    thumbnailer_name = models.CharField(max_length=64, choices=get_thumbnailer_classes(), default=get_default_thumbnailer(), null=True, blank=True, verbose_name=_("automatic thumbnail creation"))
    thumbnail_mandatory = models.BooleanField(pgettext_lazy("component field label", "Thumbnail is mandatory"), default=False)
    max_thumbnail_size = models.IntegerField(verbose_name=_("Maximum thumbnail size"), default=settings.DEFAULT_MAX_THUMB_SIZE)
    big_image_allowed = models.BooleanField(pgettext_lazy("component field label", "Big images are allowed"), default=True)
    max_big_image_size = models.IntegerField(verbose_name=_("Maximum larger image size"), default=settings.DEFAULT_MAX_IMAGE_SIZE)
    file_masks = models.CharField(_("Allowed file masks"), help_text=_("space-separated list of file masks, e.g. *.jpg"), max_length=64, default="*")

    def thumbnailer(self):
        return get_thumbnailer(self.thumbnailer_name)

    def is_filename_allowed(self, name):
        if not self.file_masks:
            #print "masks not specified for component"
            return True
        for mask in self.file_masks.split():
            if fnmatch.fnmatch(name, mask):
                #print "{} matches to {}".format(name, mask)
                return True
        return False

    def __str__(self):
        return pgettext_lazy("component title", "{0} {1}").format(self.application.title, self.title).encode('utf-8')

    def __unicode__(self):
        return pgettext_lazy("component title", "{0} {1}").format(self.application.title, self.title)

class License(models.Model):
    class Meta:
        verbose_name = _("license")
        verbose_name_plural = _("licenses")
        
    slug = models.SlugField(max_length=32, primary_key=True)
    title = models.CharField(max_length=255, verbose_name=_("Title"))
    notes = models.TextField(null=True, blank=True, verbose_name=_("Notes"))
    text = models.TextField(null=True, blank=True, verbose_name=_("Legal text"))

    def __str__(self):
        return pgettext_lazy("license title", "{0}: {1}").format(self.slug, self.title).encode('utf-8')

    def __str__(self):
        return pgettext_lazy("license title", "{0}: {1}").format(self.slug, self.title)


class Asset(models.Model):
    class Meta:
        verbose_name = _("asset")
        verbose_name_plural = _("assets")

    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_("author"))
    application = models.ForeignKey('Application', on_delete=models.CASCADE, verbose_name=_("application"))
    component = models.ForeignKey('Component', on_delete=models.CASCADE, null=True, verbose_name=_("component"))
    license = models.ForeignKey('License', on_delete=models.SET_NULL, null=True, blank=False, verbose_name=_("license"))
    original_author = models.CharField(max_length=255, null=True, blank=True, verbose_name=_("original author"))
    creation_date = models.DateTimeField(null=True, blank=True, verbose_name=_("Originally created"))
    title = models.CharField(max_length=255, verbose_name=_("title"))
    notes = models.TextField(null=True, verbose_name=_("description"))
    image = models.ImageField(upload_to=get_thumbnail_path, verbose_name=_("thumbnail"), null=True, blank=True)
    big_image = models.ImageField(upload_to=get_big_image_path, verbose_name=_("larger image"), null=True, blank=True)
    data = models.FileField(upload_to=get_data_path, verbose_name=_("data file"))
    url = models.URLField(null=True, blank=True, verbose_name=_("URL"))
    pub_date = models.DateTimeField(verbose_name=_("date published"))
    version = VersionField(null=True, blank=True, number_bits=[8,8,8,8], verbose_name=_("asset version"))
    app_version_min = VersionField(verbose_name=_("Minimum compatible application version"), null=True, blank=True, number_bits=[8,8,8,8])
    app_version_max = VersionField(verbose_name=_("Maximum compatible application version"), null=True, blank=True, number_bits=[8,8,8,8])
    tags = TaggableManager(blank=True, verbose_name=_("tags"))
    num_votes = models.PositiveIntegerField(default=0)
    votes = VotableManager(extra_field='num_votes')

    def clean(self):
        if self.component and self.data and not self.component.is_filename_allowed(self.data.name):
            raise ValidationError(_("It is not allowed to upload files of this type for this component"))

        if self.component and not self.component.big_image_allowed:
            if self.big_image:
                raise ValidationError(_("It is not allowed to upload big images for this component"))

        if self.component and self.component.thumbnail_mandatory:
            if not self.image and not (self.component and self.component.thumbnailer_name):
                raise ValidationError(_("You should upload thumbnail file"))

        super(Asset, self).clean()

    def save(self, *args, **kwargs):
        if self.data and not self.image and self.component:
            thumbnailer = self.component.thumbnailer()
            auto_thumbnail = None
            if thumbnailer:
                auto_thumbnail = thumbnailer.make_thumbnail(self.data)
            elif self.big_image:
                auto_thumbnail = thumbnail_from_big_image(self.big_image, size=self.component.max_thumbnail_size)
            if auto_thumbnail:
                # pass save=False because otherwise it would call save() recursively
                self.image.save("auto_thumbnail.png", auto_thumbnail, save=False)

        super(Asset,self).save(*args, **kwargs)

    def get_tags(self):
        return ", ".join([tag.name for tag in self.tags.all()])

    def get_app_versions(self):
        if not self.app_version_min and not self.app_version_max:
            return pgettext_lazy("application version", "any")
        if self.app_version_min and not self.app_version_max:
            return pgettext_lazy("application version", ">= {}").format(self.app_version_min)
        if not self.app_version_min and self.app_version_max:
            return pgettext_lazy("application version", "<= {}").format(self.app_version_max)
        return pgettext_lazy("application version", ">= {0} and <= {1}").format(self.app_version_min, self.app_version_max)

    def get_filename(self):
        return basename(self.data.name)

    def get_comments_count(self):
        ct = ContentType.objects.get_for_model(Asset)
        return Comment.objects.filter(content_type=ct, object_pk=self.pk).count()

    def __str__(self):
        result = ""
        if self.application:
            result += str(self.application) + " "
        if self.component:
            result += self.component.title + " "
        result += self.title
        return result.encode('utf-8')

    def __unicode__(self):
        result = ""
        if self.application:
            result += str(self.application) + " "
        if self.component:

assethub/assets/views/users.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseForbidden, HttpResponseBadRequest, JsonResponse, HttpResponseRedirect
from django.views import generic
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import ugettext as _
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from taggit.models import Tag

from assets.models import Asset, Component, Application
from assets.forms import AssetForm, UserForm, ProfileForm
from assets.views.common import get_page

@login_required
def follow(request, username):
    """POST handler for 'follow' AJAX link"""

    if request.method != 'POST':
        return HttpResponseBadRequest()
    buddy = get_object_or_404(User, username=username)
    request.user.profile.follows.add(buddy)
    response = JsonResponse({'success': True})
    return response

@login_required
def unfollow(request, username):
    """POST handler for 'unfollow' AJAX link"""

    if request.method != 'POST':
        return HttpResponseBadRequest()
    buddy = get_object_or_404(User, username=username)
    request.user.profile.follows.remove(buddy)
    response = JsonResponse({'success': True})
    return response

def current_user_profile(request):
    if request.user.is_authenticated:
        return get_user_profile(request, request.user)
    else:
        return HttpResponseForbidden()

def user_profile(request, username):
    user = get_object_or_404(User, username=username)
    return get_user_profile(request, user)

def get_user_profile(request, user):
    title = _("{0}'s profile").format(user.username)
    most_rated_assets = user.asset_set.order_by('-num_votes')[:5]
    notifications = user.notifications.unread()[:20]
    try:
        followed = request.user.profile.does_follow(user)
    except AttributeError as e:
        print(e)
        followed = False
    context = dict(buddy=user, followed=followed, title=title, most_rated_assets=most_rated_assets, notifications=notifications)
    return render(request, "assets/profile.html", context)

def get_users_list(request):
    users_list = User.objects.order_by('username')
    users = get_page(request, users_list)
    context = dict(users=users, title = _("List of users"))
    return render(request, "assets/users.html", context)

@login_required
def edit_profile(request):
    user = request.user
    if request.method == "POST":
        user_form = UserForm(request.POST, instance=user)
        profile_form = ProfileForm(request.POST, instance=user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return HttpResponseRedirect(reverse('user_profile', args=[user.username]))
    else:
        user_form = UserForm(instance=user)
        profile_form = ProfileForm(instance=user.profile)

    title = _("Edit profile")
    context = dict(user_form=user_form, profile_form=profile_form, title=title, form_action=reverse('edit_profile'))
    return render(request, 'assets/edit_profile.html', context)

assethub/assets/templates/assets/asset_common.html
{% load i18n %}
{% load markdown_deux_tags %}
{% load common %}
{% load staticfiles %}

{% if user == asset.author %}
  <p class="edit"><a href="{% url 'edit_asset' asset.pk %}">{% trans 'Edit' %}</a></p>
{% endif %}
{% if asset.tags.all %}
  <p class="tags">
  {% for tag in asset.tags.all %}
    <a class="tag" href="{% url 'by_tag' tag.slug %}">{{tag.name}}</a>
    {% if not forloop.last %}, {% endif %}
  {% endfor %}
  </p>
{% endif %}
  <div class="rating-container">
    {% if user != asset.author %}
      <p><a href="#" onclick="vote({{asset.pk}}, 'up')"><img src="{% static 'assets/vote-up.png' %}" title="{% trans 'Up' context "voting" %}"/></a></p>
    {% endif %}
    <p class="rating-value"><span class="num_votes">{{asset.num_votes}}</span></p>
    {% if user != asset.author %}
      <p><a href="#" onclick="vote({{asset.pk}}, 'down')"><img src="{% static 'assets/vote-down.png' %}" title="{% trans 'Down' context "voting" %}"/></a></p>
    {% endif %}
  </div>
<p>{% trans 'Comments' %}: {{asset.get_comments_count}}</p>

assethub/assets/templates/assets/asset_thumbnail.html
{% load staticfiles %}
{% load i18n %}

{% if as_link %}
<a href="{% url 'asset' asset.pk %}">
{% endif %}
{% if asset.image %}
  <img class="thumbnail" src="{{asset.image.url}}" alt="{{asset.title}}"/>
{% else %}
  <img alt="{% trans 'No preview available' %}" class="thumbnail" src="{% static 'assets/nopreview.png' %}" alt="{{asset.title}}"/>
{% endif %}
{% if as_link %}
</a>
{% endif %}

assethub/assets/templates/assets/asset_title.html
{% load i18n %}
{% load common %}

{% if as_link %}
  <a href="{% url 'asset' asset.pk %}">{{asset.title}}</a>
{% else %}
  {{asset.title}}
{% endif %}
{% trans 'by' %}
{% if asset.original_author %}
  {{asset.original_author}}
{% else %}
  {% user_link asset.author %}
{% endif %}

assethub/assets/templates/assets/default.html
{% load i18n %}
{% load staticfiles %}
{% load navigation %}
{% load social_auth %}
{% load notifications_tags %}
{% load common %}
{% load flatmenu_tags %}

<!doctype html>
<html>

<head>
  <meta name="google-signin-client_id" content="{% google_plus_client_id %}" />
<link rel="stylesheet" type="text/css" href="{% static 'assets/style.css' %}" />
{% block pagetitle %}
{% if title %}
<title>{{title}}</title>
{% endif %}
{% endblock %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.1/jquery.min.js"></script>
<script>
function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

var csrftoken = getCookie('csrftoken');

function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}

$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
});

function vote(id, direction) {
        $.post('/vote/'+id+'/'+direction+'/', {HTTP_X_REQUESTED:'XMLHttpRequest'},
             function(data) {
                 if (data.success == true) {
                     $('div#asset_'+id+' .num_votes').text(data.score);
                 } else {
                     alert('ERROR: ' + data.error_message);
                 }
             }, 'json'
            )
}

function follow(username) {
        $.post('/accounts/profile/'+username+'/follow/', {HTTP_X_REQUESTED:'XMLHttpRequest'},
             function(data) {
                 if (data.success == true) {
                     $('div#user_'+username+' .followtext').text("You are now following this user.");
                 } else {
                     alert('ERROR: ' + data.error_message);
                 }
             }, 'json'
            )
}

function unfollow(username) {
        $.post('/accounts/profile/'+username+'/unfollow/', {HTTP_X_REQUESTED:'XMLHttpRequest'},
             function(data) {
                 if (data.success == true) {
                     $('div#user_'+username+' .followtext').text("Now you are not following this user.");
                 } else {
                     alert('ERROR: ' + data.error_message);
                 }
             }, 'json'
            )
}
</script>

{% if post_form %}
{{post_form.media}}
{% endif %}

{% block media %}
{% endblock %}

</head>

<body>


{% get_menu_items as menu %}
<div class="topmenu">
<ul class="topmenu">
  {% for item in menu %}
    <li class="menuitem"><a href="{{item.get_url}}">{{item.title}}</a></li>
  {% endfor %}
  {% if user.is_staff %}
    <li class="menuitem"><a href="/admin/">{% trans 'Administration' %}</a></li>
  {% endif %}
  {% if user.is_authenticated %}
    {% notifications_unread as unread_count %}
    <li class="menuitem{% if unread_count > 0 %} unread{% endif %}">
      <a href="{% url 'notifications:all' %}">{% trans 'Notifications' %}</a>
    </li>
    <li class="menuitem"><a href="{% url 'logout' %}">{% trans 'Log out' %}</a></li>
  {% else %}
    <li class="menuitem"><a href="{% url 'login' %}">{% trans 'Log in' %}</a></li>
    <li class="menuitem"><a href="/accounts/register/">{% trans 'Register' %}</a></li>
  {% endif %}
</ul>
</div>

<div class="login">
{% if user.is_authenticated %}
<p>{% trans 'Hello,' context "site_greeting" %} {% user_link user %}!</p>
{% endif %}
</div>

{% block h1 %}
{% if title %}
<h1>
  <a href="/">/</a>
{{title}}
</h1>
{% endif %}
{% endblock %}

{% tree %}

<div id="rightpane">
{% if application %}
  {% if component %}
  <div id="postlink">
    <p><a href="{% url 'post_asset' application.slug component.slug %}">{% trans 'Post an asset' %}</a></p>
  </div>
  {% endif %}
{% endif %}

<div id="searchbox">
  <form action="{% url 'simple_search' %}" method="get">
    {{simple_search_form.query}}
    <input type="submit" value="{% trans 'search' %}"/>
  </form>
  <p><a href="{% url 'advanced_search' %}">{% trans 'Advanced search' %}</a></p>
</div>

{% tags %}
</div>

<div id="content">

{% block content %}
{% endblock %}

</div>

{% block endscripts %}
{% endblock %}
<script>
$(document).ready(function() {
  $('.wmd-preview').hide();
});

$('.wmd-preview-title').click(function() {
  $('.wmd-preview').slideToggle('fast');
});
</script>

</body>
</html>

assethub/assets/templates/assets/enable_api.html
{% extends 'assets/default.html' %}
{% load i18n %}

{% block content %}
<p>{% trans 'API usage is now enabled.' %}</p>
{% if use_current_password %}
<p>
{% blocktrans %}You can use your current password to access API.{% endblocktrans %}
</p>
{% else %}
<p>
{% trans 'Please use the following password for API:' %}
</p>
<center>{{new_password}}</center>
<p>
{% trans 'Pleas save this password in safe place. This password will not be shown you again if you visit this page next time.' %}
</p>
{% endif %}
{% url 'change_password' as change_password_url %}
<p>
{% blocktrans %}You may <a href="{{change_password_url}}">change your password</a> if you wish.{% endblocktrans %}
</p>
{% endblock %}

assethub/assets/templates/assets/index.html
{% extends 'assets/default.html' %}
{% load i18n %}
{% load markdown_deux_tags %}
{% load navigation %}
{% load common %}

{% block content %}
{% if application %}
{% if logo %}
<img class='logo' src='{{logo.url}}' height='48px'/>
{% endif %}
<h2>{% trans 'Application' %}: <a href="{{application.url}}">{{application}}</a></h2>
<div class="application-notes">
{{application.notes|markdown}}
</div>
{% endif %}
{% if component %}
<h2>{% trans 'Component' %}: <a href="{% url 'by_component' application.slug component.slug %}">{{component.title}}</a></h2>
<div class="component-notes">
  {{component.notes|markdown}}
</div>
{% endif %}
{% if assets %}
<div class="assets">
    {% for asset in assets %}
    <div class="asset" id="asset_{{asset.pk}}">
      <a href="{% url 'asset' asset.pk %}">
        {% asset_thumbnail asset %}
      </a>
      <div class="thumbnail-description">
        <p class="title">{% asset_title asset True %}</p>
        {% asset_common user asset False %}
      </div>
    </div>
    {% endfor %}
</div>

{% pagination assets %}

{%else%}
  <p>{% trans 'No assets available.' %}</p>
{%endif%}
{% endblock %}

assethub/assets/templates/assets/license.html
{% extends 'assets/default.html' %}
{% load i18n %}
{% load markdown_deux_tags %}

{% block content %}
<div class="license">
  <div class="license-short">
    <h2>{% trans 'Brief introduction' context "license" %}</h2>
    {{license.notes|markdown}}
  </div>

  <div class="license-text">
    <h2>{% trans 'Legal text' context "license" %}</h2>
    {{license.text|markdown}}
  </div>
</div>
{% endblock %}

assethub/assets/templates/assets/search.html
{% extends 'assets/default.html' %}
{% load i18n %}

{% block content %}
<form action="." method="get">
<table>
  {{ form.as_table }}
  <tr><td><input type="submit" value="{% trans 'Search' %}"/></td></tr>
</table>
</form>
{% endblock %}

assethub/assets/templates/assets/tree.html
{% load i18n %}
<div id="navtree">
  <h3>{% trans 'Navigation' %}</h3>
  <ul>
    {% for app in applications %}
    <li><a href="{% url 'by_application' app.slug %}">{{app.title}}</a>
      {% if app.component_set.all %}
      <ul>
      {% for component in app.component_set.all %}
      <li><a href="{% url 'by_component' app.slug component.slug %}">{{component.title}}</a></li>
      {% endfor %}
      </ul>
      {% endif %}
    </li>
    {% endfor %}
  </ul>
  
  <p><a href="{% url 'users_list' %}">{% trans 'All users' %}</a></p>
</div>